In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('analysis_id(in).csv')

In [3]:
df.head()

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isna().sum()

Unnamed: 0                   0
date_hour                    0
client                       0
device_type                  0
time_zone                    0
os_name                      0
browser_name                 0
ad_unit                      0
size                         0
bidder                       0
bid_range                    0
media_type                   0
request_count                0
response_count               0
prebid_win_count          3833
win_count                 4814
sum_bid                   1210
sum_time_to_respond       1210
median                    3240
min_bid                   1210
max_bid                   1210
avg_bid                   1210
sum_2nd_highest_bid       4266
sum_prebid_winning_bid    3833
sum_winning_bid           4814
sum_nobid                 5000
sum_timeout               5000
dtype: int64

In [2]:
df= pd.read_csv('analysis_id(in).csv')

In [10]:
df['prebid_win_count']= df['prebid_win_count'].fillna(0)

In [11]:
df.isna().sum()

Unnamed: 0                   0
date_hour                    0
client                       0
device_type                  0
time_zone                    0
os_name                      0
browser_name                 0
ad_unit                      0
size                         0
bidder                       0
bid_range                    0
media_type                   0
request_count                0
response_count               0
prebid_win_count             0
win_count                 4814
sum_bid                   1210
sum_time_to_respond       1210
median                    3240
min_bid                   1210
max_bid                   1210
avg_bid                   1210
sum_2nd_highest_bid       4266
sum_prebid_winning_bid    3833
sum_winning_bid           4814
sum_nobid                 5000
sum_timeout               5000
dtype: int64

In [32]:
win_rate=df.groupby('bidder').agg(total_bids=('request_count','sum'),
                                     total_win=('prebid_win_count','sum'))

In [33]:
win_rate

              total_bids  total_win
bidder
                  261724        0.0
33across             886      136.0
appnexus             830      175.0
criteo              3181      587.0
emx_digital          393       56.0
ix                  3051      184.0
medianet            2556      253.0
onemobile           2726      759.0
openx               1165       86.0
pubmatic            2335      255.0
pulsepoint           191       71.0
rhythmone            655      160.0
rubicon              582       33.0
sharethrough         332      104.0
sovrn                358       14.0
teads                700      323.0
triplelift          1479      108.0
undertone            104       52.0

In [41]:
win_rate['win_rate']=win_rate.apply(lambda row: row['total_win']/row['total_bids'] if row['total_bids']>0 else 0, axis=1)*100

In [42]:
win_rate.sort_values(by='win_rate', ascending=False)

              total_bids  total_win   win_rate
bidder
undertone            104       52.0  50.000000
teads                700      323.0  46.142857
pulsepoint           191       71.0  37.172775
sharethrough         332      104.0  31.325301
onemobile           2726      759.0  27.842993
rhythmone            655      160.0  24.427481
appnexus             830      175.0  21.084337
criteo              3181      587.0  18.453317
33across             886      136.0  15.349887
emx_digital          393       56.0  14.249364
pubmatic            2335      255.0  10.920771
medianet            2556      253.0   9.898279
openx               1165       86.0   7.381974
triplelift          1479      108.0   7.302231
ix                  3051      184.0   6.030810
rubicon              582       33.0   5.670103
sovrn                358       14.0   3.910615
                  261724        0.0   0.000000

In [44]:
win_rate.sort_values(by='win_rate', ascending=False).head(2)

           total_bids  total_win   win_rate
bidder
undertone         104       52.0  50.000000
teads             700      323.0  46.142857

Part1:
It's a binary classifiacation problem the probablity will be between 0 and 1.Firstly we will handle missing values, handle categorical variables and then I will take the features as X and target variable as Y, split them into train and test datasets (test size can be take as 30%) and train the model with the losgistic Regression model, and try to see the results on Y test dataset after fitting it on X test dataset

The features I will select are:
device _type: user device type can affect ad quality and compitiotion
time_zone: some time zones might have higher ad value or higher compitiotion
os_name: maybe we can include as we can correlate it with device type and it can affect auction behaviour
ad_unit: different ad units will have different ad value and compitiotions or bids
size: size can influence the cost of a add or its performance
bid_range: shows the bid strategy and how much bidder is willing to spend
request_count: more requests can help analyze more opportunities
response_count: helps to show better system performance
prebid_win_count: helps us to show who and how many times won
win_count: If it is highly same as prebid_win_count it can cause multicollinearity but in our case we have many different values
sum_bid: higher bid can show higher winning chances
sum_time_to_respond: faster response time means high chances of winning
min_bid, max_bid, avg_bid: useful to show bidding intensities
sum_2nd_highest_bid: useful for how bids are close with top

Part 2:
bid_amount: Coefficient = 0.8 -> if 1 unit in bid amount increases the probablity of winning increases by that is higher bid amount has more chance of winning
time_to_bid: Coefficient = -0.4 -> each 1 unit of delay reduces probability of by 0.4. Faster bids have compititive advantage and delays will decrease winning chances
ad_unit_A: Coefficient = 0.3 (reference category: ad_unit_B) -> when the add is shown in Ad unit A instead of ad unit B the chances of winning is 0.3. that is Ad unit A performs better in auctions than in unit B.